DROP TABLE IF EXISTS T_SYSTEM_CONFIGURATION;

ALTER TABLE T_JOB ADD CONSTRAINT `UQ_NAME` UNIQUE (A_NAME);

ALTER TABLE T_JOB MODIFY COLUMN `A_ERROR_DURATION_THRESHOLD_IN_SECONDS` bigint(20);
ALTER TABLE T_JOB MODIFY COLUMN `A_WARN_DURATION_THRESHOLD_IN_SECONDS` bigint(20);
ALTER TABLE T_JOB MODIFY COLUMN `A_EXECUTION_INTERVAL_IN_SECONDS` bigint(20);

CREATE TABLE `T_SYSTEM_CONFIGURATION` (
  `P_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `A_KEY` varchar(255) NOT NULL,
  `A_VALUE` varchar(255) NOT NULL,
  PRIMARY KEY (`P_ID`)
);

ALTER TABLE T_SYSTEM_CONFIGURATION ADD CONSTRAINT `UQ_KEY` UNIQUE (A_KEY);
ALTER TABLE T_NOTIFICATION  CHANGE COLUMN `A_ERROR_MESSAGE` `A_ERROR_MESSAGE` VARCHAR(500) NULL;

