DELETE FROM T_SYSTEM_CONFIGURATION;
INSERT INTO T_SYSTEM_CONFIGURATION VALUES (1, 'config.jobs.InstanceCompletion', '3600');
INSERT INTO T_SYSTEM_CONFIGURATION VALUES (2, 'config.jobs.InstanceStartup', '1800');
INSERT INTO T_SYSTEM_CONFIGURATION VALUES (3, 'config.jobs.offset', '5');