DROP TABLE IF EXISTS T_JOB_INSTANCE_EVENT;
CREATE TABLE `T_JOB_INSTANCE_EVENT` (
  `P_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `A_CREATE_DATE` datetime DEFAULT NULL,
  `F_JOB_INSTANCE_ID` bigint(20) NOT NULL,
  `A_STATUS` varchar(50) NOT NULL,
  `A_DESCRIPTION` text,
  PRIMARY KEY (`P_ID`)
) ENGINE=InnoDB;

ALTER TABLE T_JOB_INSTANCE_EVENT ADD CONSTRAINT `FK_JOB_INSTANCE_JOB_INSTANCE_EVENT` FOREIGN KEY (F_JOB_INSTANCE_ID) REFERENCES T_JOB_INSTANCE(P_ID);

ALTER TABLE T_JOB ADD COLUMN `A_CRITICITY` VARCHAR(500) DEFAULT 'MEDIUM';